
using Application.Services;
using Application.Services.Abstraction;
using Application.Services.Abstraction.Auth;
using Application.Services.Auth;
using Domain.Identity;
using Domain.IRepository;
using Infrastructure.Context;
using Infrastructure.Context.Configurations.Jwt;
using Infrastructure.Repository;
using Infrastructure.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;
using StackExchange.Redis;
using System.Text;

namespace Infrastructure.DependenciesInjection
{
    public static class PresistanceServiceExtensions
    {
        public static IServiceCollection AddinfrastructreServices
            (this IServiceCollection services, IConfiguration configuration)
        {
            services.AddDbContext<ApplicationDbContext>(options
                =>
            {
                var connectionString = configuration.GetConnectionString("DefaultConnection");
                options.UseSqlServer(connectionString);
            }
            );

            // Generic repository (open generic) - covers any BaseEntity that doesn't
            // have a dedicated specialized repository registered below.
            services.AddScoped(typeof(IGenericRepository<>), typeof(GenericRepository<>));

            // Entity-specific repositories
            services.AddScoped<IDepartmentRepo, DepartmentRepository>();
            services.AddScoped<IDoctorRepo, DoctorRepository>();
            services.AddScoped<ILabTechnicianRepo, LabTechnicianRepository>();
            services.AddScoped<ILabTestRepo, LabTestRepository>();
            services.AddScoped<ILabTestElementRepo, LabTestElementRepository>();
            services.AddScoped<INotificationRepo, NotificationRepository>();
            services.AddScoped<IPatientRepo, PatientRepository>();
            services.AddScoped<IPatientResultRepo, PatientResultRepository>();
            services.AddScoped<IPatientResultElementRepo, PatientResultElementRepository>();
            services.AddScoped<IRequestLabsRepo, RequestLabsRepository>();
            services.AddScoped<ISessionRepo, SessionRepository>();
            services.AddScoped<ITestElementRepo, TestElementRepository>();
            services.AddScoped<IMemberRepo, MemberRepo>();
            services.AddScoped<ILaboratoryRepo, LaboratoryRepository>();
            services.AddScoped<ILaboratoryService, LaboratoryService>();
            // Unit of Work
            services.AddScoped<IUnitOfWork, UnitOfWork>();

            // Auth-related services (Application-layer contracts, Infrastructure-layer implementations)
            services.Configure<JwtSettings>(configuration.GetSection("Jwt"));
            services.AddScoped<ITokenService, TokenService>();

            // ASP.NET Core Identity, using our custom ApplicationUser/ApplicationRole
            services.AddIdentity<ApplicationUser, ApplicationRole>(options =>
            {
                // Reasonable defaults; tune as needed.
                options.Password.RequiredLength = 8;
                options.Password.RequireNonAlphanumeric = false;
                options.User.RequireUniqueEmail = true;
            })
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            // JWT bearer authentication
            var jwtSettings = configuration.GetSection("Jwt").Get<JwtSettings>() ?? new JwtSettings();

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true,
                    ValidIssuer = jwtSettings.Issuer,
                    ValidAudience = jwtSettings.Audience,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSettings.Key)),
                    ClockSkew = TimeSpan.Zero
                };
            });

            // Permission-based authorization: a custom policy provider builds a policy
            // on the fly for every "Permission:{Name}" policy generated by
            // [HasPermission(Permissions.X)] / CheckPermissionAttributeAbstract, backed
            // by PermissionAuthorizationHandler which checks the caller's JWT claims.
            services.AddSingleton<IAuthorizationPolicyProvider, PermissionPolicyProvider>();
            services.AddScoped<IAuthorizationHandler, PermissionAuthorizationHandler>();

            services.AddControllers()
               .AddJsonOptions(options =>
                  {
                       options.JsonSerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
                  });
            services.AddAuthorization();

            return services;
        }
    }
}
